import os, sys, subprocess
import networkx as nx

'''
Parveen Gartan
12 Feb 2024
'''

rtf = open(f'{sys.argv[1]}.rtf', 'r')
prm1 = open(f'{sys.argv[1]}.prm', 'r')

resid = 'MOL'

MASS   = []
RESI  = []
ATOMS = []
BONDS = []
IMPR  = []
AT = []

try:
   os.remove(f'{sys.argv[1]}_charmm.rtf')
   os.remove(f'{sys.argv[1]}_charmm.prm')
except FileNotFoundError:
    print('File does not exists.')


out_rtf = open(f'tmp.rtf', 'a') 
out_prm = open(f'{sys.argv[1]}_charmm.prm', 'a')


#---------------- rtf ---------------------------
out_rtf.write('!CHARMM rtf file generated by AmberTools20 \n')
out_rtf.write('* \n')
out_rtf.write('  36 1 \n')

for line in rtf:
    if line.startswith('MASS'):
        x = line.split()
        out = f'{x[0]} -1 {x[2]} {x[3]}'
        #out_rtf.write(f'{out} \n')
        MASS.append(out)
    elif line.startswith('RESI'):
        y = line.split()
        out = f'{y[0]} {resid} {y[-1]}'
        RESI.append(out)
    elif line.startswith('ATOM'):
        a = line.split()
        a = f'{a[0]} {a[1]}   {a[2]}  {a[3]}'
        ATOMS.append(a)
    elif line.startswith('BOND'):
        BONDS.append(line)
    elif line.startswith('IMPH'):
        IMPR.append(line)         

for mass in MASS:
    out_rtf.write(f'{mass} \n')

out_rtf.write('AUTO ANGLES DIHE \n')
out_rtf.write(f'\n')

for resi in RESI:
    out_rtf.write(f'{resi} \n')  ## max 3 characters
for atom in ATOMS:
    out_rtf.write(f'{atom} \n')
out_rtf.write(f'\n')
for bond in BONDS:
    out_rtf.write(f'{bond}')
for impr in IMPR:
    out_rtf.write(f'{impr}')

out_rtf.write('PATCH FIRST NONE LAST NONE \n')

out_rtf.write('END \n')
out_rtf.write(f'\n')

#-------------------------------------------------------
#--------------- PRM -----------------------------------
out_prm.write('!--------------------------------------------- \n')
out_prm.write('!        Generated with AmberTools20 \n')
out_prm.write('!--------------------------------------------- \n')

out_prm.write('ATOM \n')
for mass in MASS:
    out_prm.write(f'{mass} \n')

out_prm.write(f'\n')

BONDS    = []
ANGLES   = []
DIHE     = []
IMPR     = []
NONBOND  = []

prm = [prm1]

for f in range(len(prm)):
    for line in prm[f]:
        if line[0:4] == 'BOND':
           for line in prm[f]:
               if line[0:5] == 'ANGLE':
                  break
               elif len(line.strip()) == 0 :
                  break
               x = line.split()
               out = f'{x[0]} {x[1]} {x[2]} {x[3]}'
               BONDS.append(out)
        elif line[0:5] == 'ANGLE':
             for line in prm[f]:
                 if line[0:8] == 'DIHEDRAL':
                    break
                 elif len(line.strip()) == 0 :
                    break
                 y = line.split()
                 y = f'{y[0]} {y[1]} {y[2]} {y[3]} {y[4]}'
                 ANGLES.append(y)
        elif line[0:8] == 'DIHEDRAL':
             for line in prm[f]:
                 if line[0:8] == 'IMPROPER':
                    break
                 elif len(line.strip()) == 0 :
                     break
                 elif line[0] == '!':
                     break
                 z = line.split()
                 z = f'{z[0]} {z[1]} {z[2]} {z[3]} {z[4]} {z[5]} {z[6]}'
                 DIHE.append(z)

        elif line[0:8] == 'IMPROPER':
             for line in prm[f]:
                 if line[0:9] == 'NONBONDED':
                    break
                 elif len(line.strip()) == 0 :
                    break
                 elif line[0] == '!':
                    break
                 m = line.split()
                 m = f'{m[0]} {m[1]} {m[2]} {m[3]} {m[4]} {m[5]} {m[6]}'
                 IMPR.append(m)
        elif line[15:19] == 'kcal':
             for line in prm[f]: 
                if len(line.strip()) == 0 :
                   break
                elif line[0:3] == 'END':
                    break
                n = line.split()
                n = f'{n[0]} {n[1]} {n[2]} {n[3]} {n[4]} {n[5]} {n[6]}'
                NONBOND.append(n)

##------------------------------------------

out_prm.write('BOND \n')
for bond in BONDS:
    out_prm.write(f'{bond} \n')
out_prm.write(f'\n')

out_prm.write('ANGLE \n')
for angle in ANGLES:
    out_prm.write(f'{angle} \n')
out_prm.write(f'\n')

out_prm.write('DIHEDRAL \n')
for dihe in DIHE:
    out_prm.write(f'{dihe} \n')
out_prm.write(f'\n')

out_prm.write('IMPROPER \n')
for impr in IMPR:
    out_prm.write(f'{impr} \n')
out_prm.write(f'\n')

out_prm.write(f'NONBONDED nbxmod  5 atom cdiel shift vatom vdistance vswitch - \n')
out_prm.write(f'cutnb 14.0 ctofnb 12.0 ctonnb 10.0 eps 1.0 e14fac 0.83333333 wmin 1.5 \n')
out_prm.write(f'!                Emin     Rmin/2              Emin/2     Rmin  (for 1-4s) \n')
out_prm.write(f'!             (kcal/mol)    (A) \n')

for nonb in NONBOND:
    out_prm.write(f'{nonb} \n')
out_prm.write(f'\n')
out_prm.write(f'END \n')


#quit()

##-------- CHARMM duplicate parameters check--------
#out_rtf.close()
#out_prm.close()

#charmmrun = f'/net/orinoco/pga043/charmm_nonstd/new_charmm/build_blade/charmm -i test.inp'
#subprocess.check_call(charmmrun, shell=True)

#quit()
#----------------------------------------------------

#-----------------------------------------------
#------------ add group definitions ------------
out_rtf.close()

os.system(f'./regroup.awk tmp.rtf > {sys.argv[1]}_charmm.rtf ')

try:
    os.remove('tmp.rtf')
except FileNotFoundError:
     print('No junk files exist.')



quit()
